import type { ResolvedLocale } from "./locale.js";
import type { Verdict } from "./checkkit.js";

const ja = {
  loading: "読み込み中です。",
  saved: "保存しました。",
  save: "保存",
  settingsIntro: "チェッカーの動作と表示を設定します。Jev に送るチェック項目を確認し、承認してください。",
  previewBuilding: "プレビューを組み立てています。",
  needApproval: "先に、チェックリスト全体を承認してください。",
  needApiKey: "TypeSafe の API キーを入力してください。",
  unsupported: (url: string) => `見られるのは http と https のページだけです。いまの URL は ${url || "不明"} です。`,
  idleFollow: "タブを開くと、自動でページをチェックします。",
  idleManual: "タブへの追従はオフです。必要なときにページをチェックしてください。",
  auditing: "ページを確認しています。",
  audit: "チェック",
  site: "サイト",
  body: "本文",
  classificationTitle: "本文の種類",
  classificationOld: "以前の記録には分類情報がありません。",
  classificationStatusReview: "分類保留",
  classificationStatusNotApplicable: "分類対象外",
  classificationPrimary: "主分類",
  classificationSecondary: "副分類",
  classificationConfidence: "分類の確信度",
  classificationConfidenceHelp: "確信度は選択肢の分布を表し、分類が正しい確率ではありません。",
  classificationReason: "理由",
  classificationEvidence: "分類の根拠",
  classificationReasons: {
    no_single_body: "分類する一本の本文がありません。",
    invalid_category_options: "分類の選択肢が不足しているか空です。",
    reserved_category_option: "分類の選択肢に予約済みの名前が含まれています。",
    incomplete_body: "本文全体を確認できていません。",
    no_evidence_candidates: "根拠として選べるページ上の記載がありません。",
    missing_window_answers: "本文範囲の分類回答がそろっていません。",
    missing_primary: "主分類の回答がありません。",
    unknown_primary: "主分類の回答が選択肢にありません。",
    unknown_secondary: "副分類の回答が選択肢にありません。",
    low_confidence: "分類または根拠の確信度が基準を下回っています。",
    unclear_category: "本文範囲の主分類を特定できません。",
    duplicate_categories: "同じ分類が主分類と副分類に選ばれました。",
    too_many_categories: "本文範囲に三つ以上の重要な分類があります。",
    primary_disagreement: "本文範囲ごとの主分類が一致しません。",
    unexplained_secondary: "副分類では説明できない本文範囲間の違いがあります。",
    classification_error: "本文分類の依頼に失敗したため、分類を保留しました。",
  },
  verdictLabels: { pass: "通過", fail: "警告", review: "要確認", not_applicable: "対象外", error: "エラー" } satisfies Record<Verdict, string>,
  detailsHelp: "判定と根拠を確認できます。このチェックで外部に送信するのは、Jev への評価依頼です。",
  noResult: "まだ結果がありません。チェック画面から実行してください。",
  report: "レポート",
  settings: "設定",
  pageChecks: "ページの判定",
  sentBody: "Jev が確認した本文",
  sentUnread: "Jev が確認した本文（末尾は未確認）",
  sentChunked: "Jev が確認した本文（重なりを含む複数範囲）",
  bodyTextHelp: "ページから抽出した本文です。引用箇所を選ぶと、該当箇所を確認できます。",
  noBodyText: "ページから本文を抽出できませんでした。",
  bodyWindows: "Jev に渡した本文の範囲",
  bodyWindow: (index: number, start: number, end: number) => `範囲 ${index} · 文字 ${start + 1}–${end}`,
  windowHelp: "各範囲は重なりを含みます。文字位置はこのレポートに保存した記録です。",
  windowRangesUnavailable: "この古い記録には、各範囲の位置が保存されていません。",
  bodyLength: (count: number) => `${count.toLocaleString("ja-JP")} 文字`,
  bodyLengthLabel: "本文の文字数",
  sourceBody: "記事本文",
  sourceTitle: "ページタイトル",
  sourceSiteName: "サイト名",
  sourceAuthor: "著者欄",
  sourceDescription: "ページ説明",
  sourceRelated: "表示用に追加した記載",
  sourceSelected: "Jev が選択",
  viewInBody: "本文で見る",
  viewInPageInfo: "ページ情報で見る",
  sourcePage: "ページ上の記載",
  pageInfoHelp: "チェック時に取得したページ情報です。タイトル、URL、発行元情報、本文などを Jev に渡します。HTTPS や数値の境界はコードで判定します。",
  siteName: "サイト名",
  pageDescription: "ページの説明",
  language: "ページの言語",
  links: "リンク数",
  extractionStatus: "本文の抽出",
  complete: "全文を抽出",
  incomplete: "上限で一部を切り取り",
  pageInfo: "ページ情報",
  technicalDetails: "処理の詳細",
  chartDetails: "判定の図表",
  answerProbability: "「はい」の確率",
  answerSelection: "選ばれた回答",
  choiceProbability: "選択確率",
  answerConfidence: "回答分布の確信度",
  confidenceHelp: "確信度は回答の分布を表します。判定が正しい確率ではありません。",
  score: "評価値",
  scoreConfidence: "評価値の確信度",
  probabilityDetails: "選択肢ごとの確率",
  scoreDistribution: "評価段階ごとの確率",
  history: "履歴",
  historyHelp: "この端末に保存した過去のチェック結果です。",
  historyEmpty: "履歴はありません。ページをチェックすると、ここに結果が残ります。",
  deleteRecord: "この記録を消す",
  saveOnDevice: "この端末にファイルで残す",
  checkedAt: "チェック日時",
  untitled: "無題",
  title: "タイトル",
  extract: "抽出",
  processing: "処理",
  words: "語",
  wordCountLabel: "推定語数",
  outboundHosts: "外部ホスト",
  hosts: "外部ホスト",
  noHosts: "なし",
  present: "あり",
  absent: "なし",
  author: "著者",
  https: "HTTPS",
  published: "公開日",
  pageKindLabel: "ページの種類",
  kindArticle: "記事",
  kindListing: "一覧",
  leftover: "未確認の本文あり",
  windows: (count: number) => `${count} 範囲`,
  input: "入力",
  output: "出力",
  item: "項目",
  verdict: "判定",
  remark: "寸評",
  grounds: "引用箇所",
  value: "値",
  questions: (count: number) => `判定項目 ${count}`,
  checklistTitle: "Jev に送るチェック項目",
  checklistCounts: (verdictCount: number, sourceCount: number) => `判定 ${verdictCount} 項目 · 引用箇所の選択 ${sourceCount} 項目`,
  questionText: "定義の言語",
  resultHelp: "各項目に、Jev の回答、判定、根拠として選ばれたページ上の記載を表示します。",
  mainQuestions: "ページの判定",
  referenceQuestions: "根拠箇所を選ぶ質問",
  referenceQuestionsHelp: "判定チップには影響せず、ページから引用する箇所を選びます。",
  seeExactDefinition: "Jev に送る質問と選択肢を見る",
  exactInstructions: "質問の指示",
  exactCriteria: "判定基準",
  internalId: "内部 ID",
  appliesWhen: "適用条件",
  questionCount: (count: number) => `${count} 項目`,
  checklistHelp: "判定に使う項目を表示しています。引用箇所を選ぶ質問は折りたたんでいます。各項目を開くと、質問と判定基準の原文を確認できます。",
  sourceQuestionCount: (count: number) => `根拠選択 ${count} 項目`,
  sourceQuestionFor: (label: string) => `${label} の根拠を選ぶ質問`,
  definitionLanguage: "Jev に送る質問と判定基準は英語です。下の説明には日本語訳を表示します。",
  branchYes: "はい",
  branchNo: "いいえ",
  articleOnly: "一つの文章として読める記事にだけ適用します。",
  noulBand: (passAt: number, failAt: number) =>
    `${passAt} 以上で通過。${failAt} 以下で警告。その間は要確認。`,
  scoreBand: (passAt: number, failAt: number, floor: number) =>
    `${passAt} 以上で通過。${failAt} 以下で警告。その間は要確認。確信度が ${floor} 未満なら要確認。`,
  choiceFloor: (floor: number) => `確信度が ${floor} 未満なら要確認。それ以外は、選んだラベルに対応する判定です。`,
  citeChoices:
    "選択肢は、このページから切り出した文です。要確認や警告の項目には、判定の原因に関係する文を表示します。選択結果は判定に影響しません。",
  truncatedNotice:
    "主本文が Jev の入力上限を超え、後半は確認できていません。本文の判定は通過にしません。",
  chunkedNotice: "主本文が長いので、重ねて分割し、厳しめにまとめて見ました。",
  synthesisHelp: "範囲ごとの回答と重なった箇所を合わせて、本文全体も確認します。",
  radarLabel: (title: string, parts: string) => `${title}のレーダー。${parts}`,
  keyHelp: "API キーはこの端末だけに保存します。Jev に問い合わせるとき以外には使わず、ログにも残しません。",
  connection: "接続",
  connectionHelp: "このキーは Jev へのチェック依頼に使います。",
  apiKey: "TypeSafe API キー",
  appearance: "外観",
  theme: "テーマ",
  locale: "言語",
  themeSystem: "システム",
  themeLight: "ライト",
  themeDark: "ダーク",
  localeSystem: "システム",
  themeHelp: "「システム」は、端末のライトとダークに合わせます。",
  localeHelp: "「システム」は、端末の言語に合わせます。日本語以外は英語です。",
  behavior: "動作",
  followTabHelp: "オンにすると、選択中のタブを開いたときにチェックします。",
  recheckOnChangeHelp: "ページ本文の変化を検知したあと、もう一度チェックします。",
  followTab: "タブに追従する",
  recheckOnChange: "本文が変わったらやり直す",
  debounceMs: "やり直すまでの待ち時間（ミリ秒）",
  debounceHelp: "連続した本文の変化をまとめるための待ち時間です。",
  minWordsHelp: "推定語数がこの値より少ないページでは、本文のチェックを行いません。",
  jevLimitsTitle: "Jev へのリクエスト上限",
  jevBudgetHelp:
    "state と最長の質問で 32,000 トークン、1 回のリクエストで 64,000 トークンです。収まる本文は 1 回で送り、超える場合は重なりを含む範囲に分けます。上限はすべての URL で共通です。",
  approvalTitle: "チェックリストの承認",
  approvalHelp: "Jev に送る定義を確認し、承認するとチェックを実行できます。定義が更新された場合は、もう一度確認が必要です。",
  minWords: "記事として確認する最小の本文量（推定語数）",
  ackLabel: "このチェックリスト全体を承認する。",
  approvalUncheckedWarning: "チェックリストの承認項目にチェックが入っていません。チェック機能を有効にするには、チェックを入れてください。",
  dismiss: "閉じる",
  iconNeedApproval: "チェックリストの承認が必要です",
  iconNeedApiKey: "API キーが必要です",
  iconUnsupported: "http と https のページだけです",
  iconIdleFollow: "タブに追従しています",
  iconIdleManual: "まだチェックしていません",
  iconReady: (site: string, page: string) => `サイト ${site}、本文 ${page}`,
  jevSendFailed: "Jev への送信に失敗しました。キーとネットワークを確認してください。",
  extractFailed: "このページの本文を読み取れませんでした。再読み込みして、もう一度チェックしてください。",
  noTargetTab: "対象のタブがありません。",
};

const en: typeof ja = {
  loading: "Loading.",
  saved: "Saved.",
  save: "Save",
  settingsIntro: "Choose how the checker behaves and appears. Review and accept the checklist Jev receives.",
  previewBuilding: "Building the preview.",
  needApproval: "Accept the whole checklist before auditing.",
  needApiKey: "Enter a TypeSafe API key.",
  unsupported: (url: string) => `Only http and https pages can be audited. This URL is ${url || "unknown"}.`,
  idleFollow: "A page check starts when you open a tab.",
  idleManual: "Tab following is off. Check a page when you need to.",
  auditing: "Checking page.",
  audit: "Check page",
  site: "Site",
  body: "Body",
  classificationTitle: "Content type",
  classificationOld: "This earlier report was not classified.",
  classificationStatusReview: "Classification needs review",
  classificationStatusNotApplicable: "Not applicable",
  classificationPrimary: "Primary category",
  classificationSecondary: "Secondary category",
  classificationConfidence: "Classification confidence",
  classificationConfidenceHelp: "Confidence describes the choice distribution, not the chance that the classification is correct.",
  classificationReason: "Reason",
  classificationEvidence: "Classification evidence",
  classificationReasons: {
    no_single_body: "There is no single body to classify.",
    invalid_category_options: "Category choices are missing or empty.",
    reserved_category_option: "Category choices include a reserved label.",
    incomplete_body: "The full body was not reviewed.",
    no_evidence_candidates: "There is no selectable page text for evidence.",
    missing_window_answers: "Some body windows have incomplete classification answers.",
    missing_primary: "A primary category answer is missing.",
    unknown_primary: "The primary answer is outside the supplied categories.",
    unknown_secondary: "The secondary answer is outside the supplied categories.",
    low_confidence: "The confidence for a category or its evidence is below the required floor.",
    unclear_category: "At least one window has no clear primary category.",
    duplicate_categories: "The same category was selected as both primary and secondary.",
    too_many_categories: "The body contains more than two material categories.",
    primary_disagreement: "The windows disagree about the primary category.",
    unexplained_secondary: "A secondary category does not explain the differences between windows.",
    classification_error: "The body classification request failed, so classification is held for review.",
  },
  verdictLabels: { pass: "Pass", fail: "Alert", review: "Review", not_applicable: "N/A", error: "Error" } satisfies Record<Verdict, string>,
  detailsHelp: "Review each answer alongside its source text. Page data is sent to Jev only to run this check.",
  noResult: "No result yet. Run a check from the Inspector.",
  report: "Report",
  settings: "Settings",
  pageChecks: "Page checks",
  sentBody: "Body reviewed by Jev",
  sentUnread: "Body reviewed by Jev (ending not reviewed)",
  sentChunked: "Body reviewed by Jev (overlapping windows)",
  bodyTextHelp: "The body extracted from this page. Select a cited passage to find it here.",
  noBodyText: "No body text could be extracted from the page.",
  bodyWindows: "Body ranges sent to Jev",
  bodyWindow: (index: number, start: number, end: number) => `Window ${index} · characters ${start + 1}–${end}`,
  windowHelp: "Each range includes its overlap with the next one. These positions were saved with this report.",
  windowRangesUnavailable: "This older record does not include the saved range positions.",
  bodyLength: (count: number) => `${count.toLocaleString("en-US")} characters`,
  bodyLengthLabel: "Body characters",
  sourceBody: "Article body",
  sourceTitle: "Page title",
  sourceSiteName: "Site name",
  sourceAuthor: "Author field",
  sourceDescription: "Page description",
  sourceRelated: "Related page text added for display",
  sourceSelected: "Selected by Jev",
  viewInBody: "View in body",
  viewInPageInfo: "View in page information",
  sourcePage: "Page text",
  pageInfoHelp: "Page information collected at check time. Jev receives the title, URL, publisher details, and body. Code applies HTTPS and numeric thresholds.",
  siteName: "Site name",
  pageDescription: "Page description",
  language: "Page language",
  links: "Link count",
  extractionStatus: "Body extraction",
  complete: "Full text extracted",
  incomplete: "Some text cut off at the limit",
  pageInfo: "Page information",
  technicalDetails: "Processing details",
  chartDetails: "Verdict charts",
  answerProbability: "Probability of “yes”",
  answerSelection: "Selected answer",
  choiceProbability: "Choice probability",
  answerConfidence: "Response confidence",
  confidenceHelp: "Confidence describes the answer distribution, not the chance that this result is correct.",
  score: "Score",
  scoreConfidence: "Score confidence",
  probabilityDetails: "Probability by choice",
  scoreDistribution: "Probability by rubric level",
  history: "History",
  historyHelp: "Past page checks saved on this device.",
  historyEmpty: "No history yet. Check a page and its result will appear here.",
  deleteRecord: "Delete this record",
  saveOnDevice: "Save a file on this device",
  checkedAt: "Checked",
  untitled: "Untitled",
  title: "Title",
  extract: "Extract",
  processing: "Timing",
  words: "words",
  wordCountLabel: "Approx. word count",
  outboundHosts: "outbound hosts",
  hosts: "Outbound hosts",
  noHosts: "None",
  present: "yes",
  absent: "no",
  author: "Author",
  https: "HTTPS",
  published: "Published",
  pageKindLabel: "Page type",
  kindArticle: "Article",
  kindListing: "Listing",
  leftover: "unreviewed text",
  windows: (count: number) => `${count} windows`,
  input: "in",
  output: "out",
  item: "Item",
  verdict: "Verdict",
  remark: "Remark",
  grounds: "Citation",
  value: "Value",
  questions: (count: number) => `${count} check items`,
  checklistTitle: "Checklist sent to Jev",
  checklistCounts: (verdictCount: number, sourceCount: number) => `${verdictCount} verdict checks · ${sourceCount} passage selectors`,
  questionText: "Definition language",
  resultHelp: "Each item shows Jev's answer, verdict, and the page text selected as evidence.",
  mainQuestions: "Page checks",
  referenceQuestions: "Passage selection questions",
  referenceQuestionsHelp: "These select a passage from the page and do not affect the verdict chips.",
  seeExactDefinition: "View the exact prompts and choices sent to Jev",
  exactInstructions: "Prompt instructions",
  exactCriteria: "Criteria",
  internalId: "Internal ID",
  appliesWhen: "Applies when",
  questionCount: (count: number) => `${count} items`,
  checklistHelp: "Verdict checks are listed below. Passage selectors are collapsed. Open an item to review its original prompt and criteria.",
  sourceQuestionCount: (count: number) => `${count} passage selectors`,
  sourceQuestionFor: (label: string) => `Select evidence for ${label}`,
  definitionLanguage: "Jev receives prompts and criteria in English. The descriptions below follow the interface language.",
  branchYes: "Yes",
  branchNo: "No",
  articleOnly: "Applies only when the page contains one piece of writing.",
  noulBand: (passAt: number, failAt: number) =>
    `Pass at ${passAt} or above. Alert at ${failAt} or below. Between them is Review.`,
  scoreBand: (passAt: number, failAt: number, floor: number) =>
    `Pass at ${passAt} or above. Alert at ${failAt} or below. Between them is Review. Confidence below ${floor} is Review.`,
  choiceFloor: (floor: number) =>
    `Confidence below ${floor} is Review. Otherwise the selected label sets the verdict.`,
  citeChoices:
    "The choices are passages cut from this page. Review and Alert items show a passage related to the reason for the verdict. The selection does not affect the verdict.",
  truncatedNotice:
    "The main body exceeded Jev's input limit, so its ending was not reviewed. The body lane cannot pass.",
  chunkedNotice: "The main body was long, so it was split with overlap and combined strictly.",
  synthesisHelp: "Jev also reviews the whole body using the answers for each range and the text where ranges overlap.",
  radarLabel: (title: string, parts: string) => `${title} radar. ${parts}`,
  keyHelp: "The API key stays on this device. It is used only to query Jev, and it is not written to logs.",
  connection: "Connection",
  connectionHelp: "This key is used when requesting a page check from Jev.",
  apiKey: "TypeSafe API key",
  appearance: "Appearance",
  theme: "Theme",
  locale: "Language",
  themeSystem: "System",
  themeLight: "Light",
  themeDark: "Dark",
  localeSystem: "System",
  themeHelp: "System follows the device light and dark setting.",
  localeHelp: "System follows the device language. Any language other than Japanese uses English.",
  behavior: "Behavior",
  followTabHelp: "When enabled, check the selected tab as you open pages.",
  recheckOnChangeHelp: "Run another check after a change to the page body is detected.",
  followTab: "Follow the tab",
  recheckOnChange: "Recheck when the body changes",
  debounceMs: "Wait before rechecking, in milliseconds",
  debounceHelp: "Groups nearby body changes before starting another check.",
  minWordsHelp: "Pages below this estimated word count skip body checks.",
  jevLimitsTitle: "Jev request limits",
  jevBudgetHelp:
    "The limit is 32,000 tokens for state plus the longest question, and 64,000 tokens per request. A body that fits is sent once; a longer body is split into overlapping ranges. The limits are the same for every URL.",
  approvalTitle: "Checklist approval",
  approvalHelp: "Review and accept the definitions Jev receives to enable checks. Review again whenever the definitions change.",
  minWords: "Minimum estimated word count for an article",
  ackLabel: "Accept this whole checklist.",
  approvalUncheckedWarning: "The checklist approval is not checked. Check it to enable checking.",
  dismiss: "Close",
  iconNeedApproval: "Checklist acceptance required",
  iconNeedApiKey: "API key required",
  iconUnsupported: "http and https pages only",
  iconIdleFollow: "Following the tab",
  iconIdleManual: "No check yet",
  iconReady: (site: string, page: string) => `Site ${site}, body ${page}`,
  jevSendFailed: "Sending to Jev failed. Check the key and the network.",
  extractFailed: "Could not read this page's body. Reload it and check again.",
  noTargetTab: "There is no target tab.",
};

export type Copy = typeof ja;

export function copyFor(locale: ResolvedLocale): Copy {
  return locale === "en" ? en : ja;
}
