import type { ResolvedLocale } from "./locale.js";

const ja = {
  loading: "読み込み中です。",
  saved: "保存しました。",
  save: "保存",
  previewBuilding: "プレビューを組み立てています。",
  needApproval: "先に、チェックリスト全体を承認してください。",
  needApiKey: "TypeSafe の API キーを入力してください。",
  unsupported: (url: string) => `見られるのは http と https のページだけです。いまの URL は ${url || "不明"} です。`,
  idleFollow: "タブを開くと、自動で Audit します。",
  idleManual: "タブへの追従はオフです。必要なときに Audit してください。",
  auditing: "Audit しています。",
  site: "サイト",
  body: "本文",
  detailsHelp: "このページの根拠です。ここから公開も、外部への送信もしません。",
  noResult: "まだ結果がありません。Inspector で Audit してください。",
  sentBody: "送った文",
  sentUnread: "抽出した主本文です。後ろが切れています。",
  sentChunked: "抽出した主本文です。分割して送っています。",
  history: "History",
  historyHelp: "この端末に残している過去の Audit です。ここから公開も、外部への送信もしません。",
  historyEmpty: "まだ履歴がありません。Inspector で Audit してください。",
  deleteRecord: "この記録を消す",
  saveOnDevice: "この端末にファイルで残す",
  checkedAt: "Audit した時刻",
  untitled: "無題",
  title: "タイトル",
  extract: "抽出",
  processing: "処理",
  words: "語",
  wordCountLabel: "語数",
  outboundHosts: "外部ホスト",
  hosts: "外部ホスト",
  noHosts: "なし",
  present: "あり",
  absent: "なし",
  author: "著者",
  https: "HTTPS",
  published: "公開日",
  pageKindLabel: "ページの形",
  kindArticle: "記事",
  kindListing: "一覧",
  leftover: "切れ残りあり",
  windows: (count: number) => `${count} 窓`,
  input: "入力",
  output: "出力",
  item: "項目",
  verdict: "判定",
  value: "値",
  questions: (count: number) => `質問 ${count}`,
  wholeListAgain: "一部だけの承認はできません。チェックリストを変えたら、リスト全体を承認し直してください。",
  checklistJaNote: "この文は読むための訳です。Jev に送る定義は英語のままです。",
  branchYes: "はい",
  branchNo: "いいえ",
  articleOnly: "記事があるときだけ聞きます。",
  noulBand: (passAt: number, failAt: number) =>
    `${passAt} 以上で Pass。${failAt} 以下で Alert。その間は Review。`,
  scoreBand: (passAt: number, failAt: number, floor: number) =>
    `${passAt} 以上で Pass。${failAt} 以下で Alert。その間は Review。確信度が ${floor} 未満なら Review。`,
  choiceFloor: (floor: number) => `確信度が ${floor} 未満なら Review。それ以外は、選んだラベルの判定です。`,
  citeChoices: "選択肢は、このページから切った文です。none のときは文を出しません。この選択は判定のチップを動かしません。",
  truncatedNotice:
    "主本文が Jev の入力枠を超えて切れています。切れた先は見ていません。本文レーンは Pass にしません。",
  chunkedNotice: "主本文が長いので、重ねて分割し、厳しめにまとめて見ました。",
  radarLabel: (title: string, parts: string) => `${title}のレーダー。${parts}`,
  keyHelp: "API キーはこの端末だけに保存します。Jev に問い合わせるとき以外には使わず、ログにも残しません。",
  connection: "接続",
  apiKey: "TypeSafe API キー",
  appearance: "外観",
  theme: "テーマ",
  locale: "言語",
  themeSystem: "システム",
  themeLight: "ライト",
  themeDark: "ダーク",
  localeSystem: "システム",
  themeHelp: "「システム」は、端末のライトとダークに合わせます。",
  localeHelp: "「システム」は、端末の言語に合わせます。日本語以外は英語です。",
  behavior: "動作",
  followTab: "タブに追従する",
  recheckOnChange: "本文が変わったらやり直す",
  debounceMs: "やり直すまでの待ち時間（ミリ秒）",
  jevBudgetHelp:
    "Jev の入力枠は、state と最長の質問で 32,000 トークン、1 回のリクエストで 64,000 トークンです。公式の Models の値です。収まる主本文は 1 回で送ります。超えたら重ねて分割します。この上限は URL ごとに変えません。",
  minWords: "本文とみなす最小の語数",
  ackLabel: "このチェックリスト全体を承認する。判定は根拠であり、公開、送信、遮断の許可ではない。",
  iconNeedApproval: "チェックリストの承認が必要です",
  iconNeedApiKey: "API キーが必要です",
  iconUnsupported: "http と https のページだけです",
  iconIdleFollow: "タブに追従しています",
  iconIdleManual: "まだ Audit していません",
  iconReady: (site: string, page: string) => `サイト ${site}、本文 ${page}`,
  jevSendFailed: "Jev への送信に失敗しました。キーとネットワークを確認してください。",
  extractFailed: "このページの本文を読めませんでした。再読み込みしてから、もう一度 Audit してください。",
  noTargetTab: "対象のタブがありません。",
};

const en: typeof ja = {
  loading: "Loading.",
  saved: "Saved.",
  save: "Save",
  previewBuilding: "Building the preview.",
  needApproval: "Accept the whole checklist before auditing.",
  needApiKey: "Enter a TypeSafe API key.",
  unsupported: (url: string) => `Only http and https pages can be audited. This URL is ${url || "unknown"}.`,
  idleFollow: "Opening a tab runs Audit.",
  idleManual: "Tab following is off. Run Audit when you want a check.",
  auditing: "Auditing.",
  site: "Site",
  body: "Body",
  detailsHelp: "Evidence for this page. Nothing here is published or sent.",
  noResult: "No result yet. Run Audit from Inspector.",
  sentBody: "Text sent to Jev",
  sentUnread: "Extracted body. The end was cut off.",
  sentChunked: "Extracted body. It was sent in overlapping parts.",
  history: "History",
  historyHelp: "Past Audits stored on this device. Nothing here is published or sent.",
  historyEmpty: "No history yet. Run Audit from Inspector.",
  deleteRecord: "Delete this record",
  saveOnDevice: "Save a file on this device",
  checkedAt: "Audited at",
  untitled: "Untitled",
  title: "Title",
  extract: "Extract",
  processing: "Timing",
  words: "words",
  wordCountLabel: "Words",
  outboundHosts: "outbound hosts",
  hosts: "Outbound hosts",
  noHosts: "None",
  present: "yes",
  absent: "no",
  author: "Author",
  https: "HTTPS",
  published: "Published",
  pageKindLabel: "Page kind",
  kindArticle: "Article",
  kindListing: "Listing",
  leftover: "unread remainder",
  windows: (count: number) => `${count} windows`,
  input: "in",
  output: "out",
  item: "Item",
  verdict: "Verdict",
  value: "Value",
  questions: (count: number) => `Questions ${count}`,
  wholeListAgain: "You cannot accept only part of the list. If it changes, accept the whole list again.",
  checklistJaNote: "",
  branchYes: "Yes",
  branchNo: "No",
  articleOnly: "Asked only when the page is an article.",
  noulBand: (passAt: number, failAt: number) =>
    `Pass at ${passAt} or above. Alert at ${failAt} or below. Between them is Review.`,
  scoreBand: (passAt: number, failAt: number, floor: number) =>
    `Pass at ${passAt} or above. Alert at ${failAt} or below. Between them is Review. Confidence below ${floor} is Review.`,
  choiceFloor: (floor: number) =>
    `Confidence below ${floor} is Review. Otherwise the selected label sets the verdict.`,
  citeChoices:
    "The choices are sentences cut from this page. none shows no sentence. This choice does not change the verdict chip.",
  truncatedNotice:
    "The main body is longer than Jev's input window. The rest was not reviewed. The body lane does not pass.",
  chunkedNotice: "The main body was long, so it was split with overlap and combined strictly.",
  radarLabel: (title: string, parts: string) => `${title} radar. ${parts}`,
  keyHelp: "The API key stays on this device. It is used only to query Jev, and it is not written to logs.",
  connection: "Connection",
  apiKey: "TypeSafe API key",
  appearance: "Appearance",
  theme: "Theme",
  locale: "Language",
  themeSystem: "System",
  themeLight: "Light",
  themeDark: "Dark",
  localeSystem: "System",
  themeHelp: "System follows the device light and dark setting.",
  localeHelp: "System follows the device language. Any language other than Japanese uses English.",
  behavior: "Behavior",
  followTab: "Follow the tab",
  recheckOnChange: "Recheck when the body changes",
  debounceMs: "Wait before rechecking, in milliseconds",
  jevBudgetHelp:
    "Jev's input window is 32,000 tokens for state plus the longest question, and 64,000 tokens per request. Those are the official Models limits. A body that fits is sent once. A longer body is split with overlap. The limit is the same for every URL.",
  minWords: "Minimum words to treat the page as a body",
  ackLabel:
    "I accept this whole checklist. A verdict is evidence. It is not permission to publish, send, or block.",
  iconNeedApproval: "Checklist acceptance required",
  iconNeedApiKey: "API key required",
  iconUnsupported: "http and https pages only",
  iconIdleFollow: "Following the tab",
  iconIdleManual: "No audit yet",
  iconReady: (site: string, page: string) => `Site ${site}, body ${page}`,
  jevSendFailed: "Sending to Jev failed. Check the key and the network.",
  extractFailed: "Could not read the body of this page. Reload it and run Audit again.",
  noTargetTab: "There is no target tab.",
};

export type Copy = typeof ja;

export function copyFor(locale: ResolvedLocale): Copy {
  return locale === "en" ? en : ja;
}
