import type { ResolvedLocale } from "./locale.js";

const ja = {
  loading: "読み込み中…",
  saved: "Saved.",
  previewBuilding: "プレビューを組み立てています…",
  splitLanes: "サイトと本文を分ける。一つの点数にはしない。",
  needApproval: "チェックリスト全体の承認が先。",
  needApiKey: "TypeSafe の API キーがまだない。",
  unsupported: (url: string) => `http(s) だけ。いまの URL は ${url || "（不明）"}。`,
  idleFollow: "タブを開くと自動で Audit する。",
  idleManual: "Follow tab オフ。必要なときだけ。",
  auditing: "Auditing…",
  site: "サイト",
  body: "本文",
  footer: "アイコン上段がサイト、下段が本文。根拠であり遮断しない。Follow tab",
  detailsHelp: "判断材料。ここから公開も送信もしない。",
  noResult: "まだ結果がありません。Inspector から Audit してください。",
  sentBody: "送った文",
  sentUnread: "抽出した主本文（切れ残りあり）",
  sentChunked: "抽出した主本文（分割して送信）",
  history: "履歴",
  untitled: "（無題）",
  title: "標題",
  extract: "抽出",
  processing: "処理",
  words: "語",
  outboundHosts: "外部ホスト",
  present: "あり",
  absent: "なし",
  author: "著者",
  leftover: "切れ残りあり",
  windows: (count: number) => `${count} 窓`,
  input: "入力",
  output: "出力",
  item: "項目",
  verdict: "判定",
  value: "値",
  questions: (count: number) => `質問 ${count}`,
  wholeListAgain: "差分承認はしない。変えたらこのリスト全体をもう一度。",
  truncatedNotice:
    "主本文が Jev の入力枠でカバーできる量を超えて切れているため、続きは精査していません。本文レーンは通過にしません。",
  chunkedNotice: "主本文が長いため重ねて分割し、厳しめに合成して精査しました。",
  radarLabel: (title: string, parts: string) => `${title}のレーダー。${parts}`,
  keyHelp: "キーは端末内だけ。Jev への問い合わせ以外には使わない。ログにも出さない。",
  connection: "接続",
  apiKey: "TypeSafe API キー",
  appearance: "外観",
  theme: "テーマ",
  locale: "言語",
  themeSystem: "システム",
  themeLight: "ライト",
  themeDark: "ダーク",
  localeSystem: "システム",
  themeHelp: "未設定は端末のライト / ダークに合わせる。",
  localeHelp: "未設定は端末の言語に合わせる。日本語以外は英語。",
  behavior: "動作",
  recheckOnChange: "本文が変わったらやり直す",
  debounceMs: "やり直しまでの待ち（ミリ秒）",
  jevBudgetHelp:
    "Jev の入力枠は state と最長の質問で 32k トークン、1 リクエスト 64k（公式 Models）。収まる主本文は 1 回で送り、超えたら重ねて分割する。URL ごとに変えない。",
  minWords: "本文とみなす最小語数",
  ackLabel: "上のチェックリスト全体を承認する。判定は根拠であり、公開・送信・遮断の許可ではない。",
  iconNeedApproval: "チェックリストの承認が必要です",
  iconNeedApiKey: "API キーが必要です",
  iconUnsupported: "http(s) のページだけ",
  iconReady: (site: string, page: string) => `サイト: ${site} / 本文: ${page}`,
  jevSendFailed: "Jev への送信に失敗しました。キーとネットワークを確認してください。",
  extractFailed: "このページからは本文を取れません。再読み込みしてからもう一度。",
  noTargetTab: "対象のタブがありません。",
};

const en: typeof ja = {
  loading: "Loading…",
  saved: "Saved.",
  previewBuilding: "Building preview…",
  splitLanes: "Site and body are separate. There is no single score.",
  needApproval: "Accept the whole checklist first.",
  needApiKey: "No TypeSafe API key yet.",
  unsupported: (url: string) => `http(s) only. Current URL is ${url || "(unknown)"}.`,
  idleFollow: "Opening a tab starts Audit automatically.",
  idleManual: "Follow tab is off. Run it when you need it.",
  auditing: "Auditing…",
  site: "Site",
  body: "Body",
  footer: "Icon top is site, bottom is body. Evidence only; it does not block. Follow tab",
  detailsHelp: "Working notes. Nothing is published or sent from here.",
  noResult: "No result yet. Run Audit from Inspector.",
  sentBody: "Sent text",
  sentUnread: "Extracted body (unread remainder)",
  sentChunked: "Extracted body (sent in windows)",
  history: "History",
  untitled: "(untitled)",
  title: "Title",
  extract: "Extract",
  processing: "Timing",
  words: "words",
  outboundHosts: "outbound hosts",
  present: "yes",
  absent: "no",
  author: "author",
  leftover: "unread remainder",
  windows: (count: number) => `${count} windows`,
  input: "in",
  output: "out",
  item: "Item",
  verdict: "Verdict",
  value: "Value",
  questions: (count: number) => `Questions ${count}`,
  wholeListAgain: "No partial ack. If the list changes, accept the whole list again.",
  truncatedNotice:
    "The main body is larger than Jev’s input window, so the rest was not reviewed. The body lane does not pass.",
  chunkedNotice: "The main body was long, so it was split with overlap and synthesized strictly.",
  radarLabel: (title: string, parts: string) => `${title} radar. ${parts}`,
  keyHelp: "The key stays on this device. It is used only to query Jev, and it is not logged.",
  connection: "Connection",
  apiKey: "TypeSafe API key",
  appearance: "Appearance",
  theme: "Theme",
  locale: "Language",
  themeSystem: "System",
  themeLight: "Light",
  themeDark: "Dark",
  localeSystem: "System",
  themeHelp: "System follows the device light / dark setting.",
  localeHelp: "System follows the device language. Anything other than Japanese uses English.",
  behavior: "Behavior",
  recheckOnChange: "Recheck when the body changes",
  debounceMs: "Wait before rechecking (ms)",
  jevBudgetHelp:
    "Jev’s input window is 32k tokens for state plus the longest question, 64k per request (official Models). A body that fits is sent once; if it does not fit it is split with overlap. This does not change per URL.",
  minWords: "Minimum words to treat as body",
  ackLabel: "Accept this whole checklist. The verdict is evidence, not permission to publish, send, or block.",
  iconNeedApproval: "Checklist acceptance required",
  iconNeedApiKey: "API key required",
  iconUnsupported: "http(s) pages only",
  iconReady: (site: string, page: string) => `Site: ${site} / Body: ${page}`,
  jevSendFailed: "Sending to Jev failed. Check the key and the network.",
  extractFailed: "This page cannot yield a body. Reload and try again.",
  noTargetTab: "There is no target tab.",
};

export type Copy = typeof ja;

export function copyFor(locale: ResolvedLocale): Copy {
  return locale === "en" ? en : ja;
}
